### ISSUE TITLE
nfsclient not installed

### ISSUE THREAD

**Issue by lnielsen** [cal/vagrant-ubuntu-precise-64#3]
Hi,

The script is great. Just one tiny issues - it doesn't install nfsclient by default which means you have to install it yourself afterwards to setup a NFS shared folder in the Vagrantfile - eg the following won't work until you've manually have run "sudo apt-get install nfsclient" in the VM:

config.vm.share_folder "v-src", "/vagrant_src", "~/src", :nfs => true

**Comment by cal** [comment]
that should be fixable..
