### ISSUE TITLE
Problem with init?

### ISSUE THREAD

**Issue by rmoriz** [cal/vagrant-ubuntu-precise-64#5]
Seems not to work, VirtualBox also says no boot medium found...

```
./build.sh 
Cleaning Custom build directories...
Downloading ubuntu-12.04-alternate-amd64.iso ...
Creating Custom ISO
Untarring downloaded ISO ...
gnutar: This does not look like a tar archive
gnutar: Skipping to next header
gnutar: Error exit delayed from previous errors
Backing up current init.rd ...
chmod: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install: No such file or directory
chmod: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install/initrd.gz: No such file or directory
mv: rename /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install/initrd.gz to /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install/initrd.gz.org: No such file or directory
Installing new initrd.gz ...
gzip: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install/initrd.gz.org.gz: No such file or directory
0 blocks
./build.sh: line 70: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install/initrd.gz: No such file or directory
Cleaning up Permissions ...
chmod: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install: No such file or directory
chmod: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install/initrd.gz: No such file or directory
chmod: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install/initrd.gz.org: No such file or directory
Replacing isolinux config ...
chmod: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/isolinux: No such file or directory
chmod: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/isolinux/isolinux.cfg: No such file or directory
rm: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/isolinux/isolinux.cfg: No such file or directory
cp: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/isolinux/isolinux.cfg: No such file or directory
chmod: /tmp/vagrant-ubuntu-precise-64/build/iso/custom/isolinux/isolinux.bin: No such file or directory
Add late_command script ...
Running mkisofs ...
mkisofs: Uh oh, I cant find the boot catalog directory 'isolinux' inside the target tree.
Creating VM Box...
Virtual machine 'ubuntu-precise-64' is created and registered.
UUID: eec9209c-f29a-4a27-8f74-3a44b163c50a
Settings file: '/tmp/vagrant-ubuntu-precise-64/build/vbox/ubuntu-precise-64/ubuntu-precise-64.vbox'
VBoxManage: error: Could not find file for the medium '/tmp/vagrant-ubuntu-precise-64/build/iso/custom.iso' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Medium, interface IMedium, callee nsISupports
Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, AccessMode_ReadWrite, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 210 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/tmp/vagrant-ubuntu-precise-64/build/iso/custom.iso"
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
```

**Comment by tigris** [comment]
What OS are you running this on?

`gnutar: This does not look like a tar archive` concerns me, since this build script is not compatible with GNU version of tar, it requires the OSX version of tar that can untar ISO files. I suspect you are perhaps not on OSX?

**Comment by rmoriz** [comment]
I tried both OSX' BSD tar and gnu-tar (which is a bit more verbose).

**Comment by tigris** [comment]
Can you paste the error output from the BSD tar? As mentioned the GNU tar is not supported by @cal 's version of this script so the above error messages crap out trying to untar the ISO and the rest from that point on is irrelevant.

**Comment by rmoriz** [comment]
see https://gist.github.com/2760539
and
https://img.skitch.com/20120521-c1nnhjp7dt9nghx8jkkdnaa47f.jpg

thanks

**Comment by tigris** [comment]
The issue is most likely in here:

`mv: rename /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install/initrd.gz to /tmp/vagrant-ubuntu-precise-64/build/iso/custom/install/initrd.gz.org: No such file or directory`

I suspect something has gone wrong in the untar. Can you change line 56 of build .sh and put a v in the middle of -xf so it reads `tar -C "${FOLDER_ISO_CUSTOM}" -xvf "${ISO_FILENAME}"` and gist the output again, I suspect this will give us a better indication of where the untar is dying.

**Comment by rmoriz** [comment]
how should tar be able to exctract files out of an .iso image?!

**Comment by tigris** [comment]
`This implementation can extract from tar, pax, cpio, zip, jar, ar, and ISO 9660 cdrom images`

From the BSD tar man page: http://people.freebsd.org/~kientzle/libarchive/man/bsdtar.1.txt

**Comment by rmoriz** [comment]
```
➜  example  which tar
/usr/bin/tar
➜  example  tar --version 
bsdtar 2.8.3 - libarchive 2.8.3
➜  example  file ubuntu-12.04-alternate-amd64.iso
ubuntu-12.04-alternate-amd64.iso: ISO 9660 CD-ROM filesystem data 'Ubuntu 12.04 LTS amd64         ' (bootable)
➜  example  tar xfv ubuntu-12.04-alternate-amd64.iso
➜  example  ls
ubuntu-12.04-alternate-amd64.iso
➜  example  
```

(return code of tar is 0!)

OSX 10.7.4

**Comment by tigris** [comment]
At this stage I am out of ideas then. I don't have an OSX machine to test on, perhaps original author @cal can help you.

**Comment by fh** [comment]
Same issue here, same tar version here:

fh-dp:tmp fh$ tar xvf /Users/fh/dev/vagrant-ubuntu-precise-64/build/iso/ubuntu-12.04-alternate-amd64.iso 
fh-dp:tmp fh$ tar tvf /Users/fh/dev/vagrant-ubuntu-precise-64/build/iso/ubuntu-12.04-alternate-amd64.iso 
fh-dp:tmp fh$

**Comment by fh** [comment]
I do have some debugging info:

The tar command is working on 10.7.3, and is not working on 10.7.4. While the tar version claims to be the same, judged by the md5sum the binary apparently has been changed:

The working OS:

```
fh-alu:tmp fh$ md5 /usr/bin/tar
MD5 (/usr/bin/tar) = c30bf82242ace672c389637fb1cae1b6
fh-alu:tmp fh$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3
```

The broken one:

```
fh-dp:tmp fh$ md5 /usr/bin/tar
MD5 (/usr/bin/tar) = 81f5825da23367b6e907fa49be378161
fh-dp:tmp fh$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3
```

**Comment by dylanvee** [comment]
Broken on 10.7.4 here too.

**Comment by cal** [comment]
Oi, this looks bad. I see that my machine is on 10.7.4 as well, not sure when it was updated. I was using something else to extract the iso initially, but that didn't work when rebuilding, so I had to use tar.

**Comment by fh** [comment]
maybe mount with hdiutil, and copy from there?

**Comment by cal** [comment]
That's what didn't work initially, for some reason. Time to try again!

**Comment by fh** [comment]
Good luck - my first fiddling here did not work as well, since the image is NTFS, hence apparently not mount-able by default.

If you need any further debugging regarding 10.7.3/10.7.4, please let me know, I still have both versions here at my hands. However, the bsdtar binary itself doesnt seem to be the problem, since the problem persists with the old binary on 10.7.4 well. libSystem.B.dylib version has been changed, too, maybe there is the issues cause.

**Comment by dylanvee** [comment]
hdiutil wouldn't mount it for me either. As an alternative, official 12.04 Vagrant boxes [have been uploaded.](https://groups.google.com/d/topic/vagrant-up/sIbKfZinu8U/discussion) They intend to make 12.04 the default box for Vagrant soon.

**Comment by rmoriz** [comment]
I ended up using https://github.com/jedi4ever/veewee (master/head not gem) to create a 12.04 box

**Comment by cal** [comment]
Default vagrant boxes and veewee are probably the saner alternatives.

I'm knee deep in libraries now.. just wondering when this problem was introduced. OS X or Xcode update?

**Comment by cal** [comment]
Fwiw, I got it working by using the macports bsdtar

```
$ /opt/local/bin/bsdtar -tvvvf ubuntu-12.04-alternate-amd64.iso
dr-xr-xr-x  12 0      0        2048 Apr 25 18:07 .
dr-xr-xr-x  2 0      0        2048 Apr 25 18:06 ./.disk
dr-xr-xr-x  3 0      0        2048 Apr 25 18:07 ./boot
dr-xr-xr-x  3 0      0        2048 Apr 25 18:07 ./boot/grub
dr-xr-xr-x  2 0      0       22528 Apr 23 20:59 ./boot/grub/x86_64-efi
dr-xr-xr-x  3 0      0        2048 Apr 25 18:06 ./dists
dr-xr-xr-x  4 0      0        2048 Apr 25 18:07 ./dists/precise
dr-xr-xr-x  7 0      0        2048 Apr 25 18:07 ./dists/precise/main
dr-xr-xr-x  2 0      0        2048 Apr 25 18:07 ./dists/precise/main/binary-amd64
... snip ...
-r--r--r--  1 0      0          55 Apr 25 18:07 ./boot/grub/loopback.cfg
-r--r--r--  1 0      0     1550134 Apr 20 19:33 ./dists/precise/main/dist-upgrader/binary-all/precise.tar.gz
-r--r--r--  1 0      0         198 Apr 20 19:49 ./dists/precise/main/dist-upgrader/binary-all/precise.tar.gz.gpg
-r--r--r--  1 0      0      136202 Mar 13 18:07 ./dists/precise/main/dist-upgrader/binary-amd64/libapt-inst1.4_0.8.16~exp12ubuntu6~upgrader1_amd64.deb
-r--r--r--  1 0      0      628756 Mar 13 18:07 ./dists/precise/main/dist-upgrader/binary-amd64/libapt-pkg4.12_0.8.16~exp12ubuntu6~upgrader1_amd64.deb
-r--r--r--  1 0      0      190356 Mar 13 18:07 ./dists/precise/main/dist-upgrader/binary-amd64/release-upgrader-libapt-pkg-dev_0.8.16~exp12ubuntu6~upgrader1_amd64.deb
-r--r--r--  1 0      0      416616 Jan 30 20:05 ./dists/precise/main/dist-upgrader/binary-amd64/release-upgrader-python-apt_0.8.0ubuntu9~upgrader3_amd64.deb
-r--r--r--  1 0      0       14160 Oct 19  2011 ./isolinux/splash.pcx
-r--r--r--  1 0      0       48038 Apr 16 16:04 ./pool/main/s/syslinux-legacy/syslinux-legacy_3.63+dfsg-2ubuntu5_amd64.deb
Archive Format: ISO9660 with Rockridge extensions,  Compression: none

$ md5 /opt/local/bin/bsdtar 
MD5 (/opt/local/bin/bsdtar) = a95b0581a4ee4eb336dd2ac8dba32a3e

$ /opt/local/bin/bsdtar --version
bsdtar 2.8.4 - libarchive 2.8.4

$ otool -L /opt/local/bin/bsdtar 
/opt/local/bin/bsdtar:
    /opt/local/lib/libarchive.2.dylib (compatibility version 11.0.0, current version 11.4.0)
    /opt/local/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.6)
    /opt/local/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.8.0)
    /opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.6)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
    /opt/local/lib/libiconv.2.dylib (compatibility version 8.0.0, current version 8.1.0)
    /opt/local/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by cal** [comment]
So that's `sudo port install libarchive` to solve it.. hmm.

**Comment by dylanvee** [comment]
Or perhaps `brew install https://raw.github.com/Homebrew/homebrew-dupes/master/libarchive.rb` for Homebrew

**Comment by tigris** [comment]
Personally I think the best solution is to not rely on tar being able to untar the ISO file, since most tar's cannot.

In my fork to make it work on linux I am just using plain mount, I presume this work on OSX?

https://github.com/tigris/vagrant-ubuntu-precise-64/blob/master/build.sh#L55

**Comment by cal** [comment]
Unfortunately [there's no -o loop on OSX](https://developer.apple.com/library/mac/#documentation/Darwin/Reference/Manpages/man8/mount.8.html) :(

I was testing an approach using hdiutil earlier, that works kind of like that, but I didn't manage to build a remastered iso from it. Also it seemed like hdiutil was affected by the same thing as tar on the current version of OSX?

**Comment by npinto** [comment]
FYI, it works on my Linux box with `libarchive` installed and `alias tar=bsdtar cpio=bsdio`.

**Comment by inthecloud247** [comment]
In brew, you can install gnu-tar... but I'm going to use veewee instead anyhow.
